CREATE TABLE [Integration].[DataSources]
(
	[Id] INT IDENTITY(1,1) PRIMARY KEY,
    [Name] VARCHAR(50) NOT NULL,
	[Summary] VARCHAR(350) NULL,
	[Updated] DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    [Created] DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
