CREATE TABLE [Integration].[DataSources]
(
	[Id] INT IDENTITY(1,1) PRIMARY KEY,
    [Name] VARCHAR(20) NOT NULL,
	[Description] VARCHAR(250) NULL,
	[Updated] DATETIME NOT NULL DEFAULT GETDATE(), 
    [Created] DATETIME NOT NULL DEFAULT GETDATE()
)
