CREATE TABLE [Environment].[Locations]
(
	[Id] INT IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(25) NOT NULL,
	[Path] VARCHAR(300) NOT NULL, 
    [Updated] DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    [Created] DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
